spring:
  application:
    name: ShlyapOff

  datasource:
    # Читаем URL из переменной окружения SPRING_DATASOURCE_URL. Если её нет — используем локальный адрес
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shlyapoff_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect <-- УДАЛЯЕМ эту строку (Hibernate сам всё понял)
        format_sql: true
    show-sql: false
    open-in-view: false # <-- ДОБАВЛЯЕМ. Это лучшая практика, отключает ленивую загрузку БД во время рендеринга HTML

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


app:
  upload:
    # папка с картинками
    dir: ${UPLOAD_DIR:./uploads}

spring.threads.virtual.enabled: true